### ISSUE TITLE
 Capping framerate of desktop? 

### ISSUE THREAD

**Issue by kq01526** [torkel104/libstrangle#17]
Hi @torkel104 ,

Is it possible to cap the framerate of the desktop?

I'd like to try how the desktop feels at 30 fps, to simulate what it would feel like when connecting a HDMI 1.4 device (limited to 3840x2160@30Hz) to a UHD TV.

I can not set the refresh rate to 30 Hz on my 60 Hz monitor, so I'd like to cap the framerate to 30 fps, to simulate what it would feel like at 30 Hz.

Is this possible with libstrangle?

Regards

**Comment by torkel104** [comment]
After some reading I managed to do this.
https://unix.stackexchange.com/questions/85383/how-to-start-a-second-x-session
https://en.wikibooks.org/wiki/Guide_to_X11/Starting_Sessions

Make sure you know how to switch between TTYs before you proceed. The command is `Ctrl + Alt + {F1-F12}`. `Ctrl + Alt + F7` will take you back to your normal X server. `Ctrl + Alt + F8` will bring up the new X server that you will spawn.

Find out which command starts your desktop. For me it was `startkde`, for gnome it might be `gnome-session`. Now press `Ctrl + Alt + F1` to go to a terminal (because you don't want to spawn X from within X). Log in. Here's the command I used:
`strangle 30 xinit startkde -- :1`
`-- :1` tells xinit to create a new X server. Replace startkde with whatever starts your desktop.

Log out from the new desktop session to stop that X server.

Good luck!
